"""adds username colum to users table

Revision ID: 04950b433181
Revises: 07149cbccf92
Create Date: 2021-06-21 17:45:59.229684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04950b433181'
down_revision = '07149cbccf92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
