"""changes relationship in table users

Revision ID: 07149cbccf92
Revises: 
Create Date: 2021-06-21 14:08:20.929730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07149cbccf92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('comments',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_table('user_info',
    sa.Column('info_id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.String(length=100), nullable=True),
    sa.Column('profile_photo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('info_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=100), nullable=True),
    sa.Column('lname', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('user_info', sa.Integer(), nullable=True),
    sa.Column('comments_added', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comments_added'], ['comments.comment_id'], ),
    sa.ForeignKeyConstraint(['user_info'], ['user_info.info_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('blogs',
    sa.Column('blog_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.Column('datePosted', sa.DateTime(), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Integer(), nullable=True),
    sa.Column('posted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['categories.category_id'], ),
    sa.ForeignKeyConstraint(['comment'], ['comments.comment_id'], ),
    sa.ForeignKeyConstraint(['posted_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('blog_id')
    )
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('role_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    op.drop_table('blogs')
    op.drop_table('users')
    op.drop_table('user_info')
    op.drop_table('comments')
    op.drop_table('categories')
    # ### end Alembic commands ###
