"""adds photo path colmn to blogs table

Revision ID: 77192c48a27e
Revises: a3edcc8e94ef
Create Date: 2021-06-22 07:47:26.217834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77192c48a27e'
down_revision = 'a3edcc8e94ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('photo_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'photo_path')
    # ### end Alembic commands ###
