"""relinks relationship btwn comment and user, user and role

Revision ID: a3edcc8e94ef
Revises: 04950b433181
Create Date: 2021-06-21 18:30:16.623897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3edcc8e94ef'
down_revision = '04950b433181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('roles_user_fkey', 'roles', type_='foreignkey')
    op.drop_column('roles', 'user')
    op.add_column('users', sa.Column('user_role', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['user_role'], ['role_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'user_role')
    op.add_column('roles', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('roles_user_fkey', 'roles', 'users', ['user'], ['user_id'])
    # ### end Alembic commands ###
