"""adds subscribed column to users table

Revision ID: b51af130f965
Revises: 77192c48a27e
Create Date: 2021-06-23 06:52:51.189187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b51af130f965'
down_revision = '77192c48a27e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscribed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscribed')
    # ### end Alembic commands ###
